services:
  - type: web
    name: property-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python
    pythonVersion: 3.11.9